// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXLVuYfDFQLLYosprI5p1kPQV9T_LU4gA',
    appId: '1:807085631825:web:af5ea531b497b1ffdd4b70',
    messagingSenderId: '807085631825',
    projectId: 'note-taking-app-38f57',
    authDomain: 'note-taking-app-38f57.firebaseapp.com',
    storageBucket: 'note-taking-app-38f57.firebasestorage.app',
    measurementId: 'G-F9YQSNDHGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC84GsO4KI97fcBSQBiqC5t4BdGubdQszo',
    appId: '1:807085631825:android:8477315901650af0dd4b70',
    messagingSenderId: '807085631825',
    projectId: 'note-taking-app-38f57',
    storageBucket: 'note-taking-app-38f57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCj1v3o3T-vqy24YfDUsdMcnDO4LNF_-A',
    appId: '1:807085631825:ios:94510d04ab79350edd4b70',
    messagingSenderId: '807085631825',
    projectId: 'note-taking-app-38f57',
    storageBucket: 'note-taking-app-38f57.firebasestorage.app',
    iosBundleId: 'com.example.notestakingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCj1v3o3T-vqy24YfDUsdMcnDO4LNF_-A',
    appId: '1:807085631825:ios:94510d04ab79350edd4b70',
    messagingSenderId: '807085631825',
    projectId: 'note-taking-app-38f57',
    storageBucket: 'note-taking-app-38f57.firebasestorage.app',
    iosBundleId: 'com.example.notestakingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXLVuYfDFQLLYosprI5p1kPQV9T_LU4gA',
    appId: '1:807085631825:web:6a767431c3c55795dd4b70',
    messagingSenderId: '807085631825',
    projectId: 'note-taking-app-38f57',
    authDomain: 'note-taking-app-38f57.firebaseapp.com',
    storageBucket: 'note-taking-app-38f57.firebasestorage.app',
    measurementId: 'G-PWQGYB8EZ8',
  );

}